from typing import Protocol
class Store(Protocol):
 def put_job(self,job): ...
 def get_job(self,job_id): ...
 def put_result(self,job_id,result): ...
 def get_result(self,job_id): ...
class MemoryStore:
 def __init__(self): self.jobs={}; self.results={}
 def put_job(self,job): self.jobs[job.job_id]=job
 def get_job(self,job_id): return self.jobs.get(job_id)
 def put_result(self,job_id,result): self.results[job_id]=result
 def get_result(self,job_id): return self.results.get(job_id)
